#!/usr/bin/env python3
"""
Convert LVGL .bin files to C source files
"""

import os
import sys

# Image configurations: (bin_filename, c_filename, variable_name, width, height)
IMAGES = [
    ("Fuel_Temp.bin", "ui_img_fuel_temp_png.c", "ui_img_fuel_temp_png", 480, 480),
    ("Oil_Temp.bin", "ui_img_oil_temp_png.c", "ui_img_oil_temp_png", 480, 480),
    ("Rev_Counter.bin", "ui_img_rev_counter_png.c", "ui_img_rev_counter_png", 480, 480),
    ("Rev_Fuel.bin", "ui_img_rev_fuel_png.c", "ui_img_rev_fuel_png", 480, 480),
    ("Temp_Exhaust.bin", "ui_img_temp_exhaust_png.c", "ui_img_temp_exhaust_png", 480, 480),
]

def convert_bin_to_c(bin_file, c_file, var_name, width, height):
    """Convert a .bin file to a C source file with LVGL image descriptor"""
    
    if not os.path.exists(bin_file):
        print(f"Error: {bin_file} not found!")
        return False
    
    # Read binary data
    with open(bin_file, 'rb') as f:
        data = f.read()
    
    data_size = len(data)
    print(f"Converting {bin_file} ({data_size} bytes) -> {c_file}")
    
    # Generate C file
    with open(c_file, 'w') as f:
        # Header
        f.write("// This file was generated by convert_bins.py\n")
        f.write(f"// Source: {bin_file}\n\n")
        f.write('#include "ui.h"\n\n')
        
        # Attributes
        f.write('#ifndef LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#define LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#endif\n\n')
        
        var_upper = var_name.upper()
        f.write(f'#ifndef LV_ATTRIBUTE_IMG_{var_upper}\n')
        f.write(f'#define LV_ATTRIBUTE_IMG_{var_upper}\n')
        f.write('#endif\n\n')
        
        # Image data array
        f.write(f'const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{var_upper} uint8_t {var_name}_map[] = {{\n')
        
        # Write data as hex bytes, 16 per line
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'  {hex_bytes},\n')
        
        f.write('};\n\n')
        
        # Image descriptor (LVGL v8 format)
        f.write(f'const lv_img_dsc_t {var_name} = {{\n')
        f.write('  .header = {\n')
        f.write('    .always_zero = 0,\n')
        f.write('    .reserved = 0,\n')
        f.write('    .cf = LV_IMG_CF_TRUE_COLOR,\n')
        f.write(f'    .w = {width},\n')
        f.write(f'    .h = {height},\n')
        f.write('  },\n')
        f.write(f'  .data_size = sizeof({var_name}_map),\n')
        f.write(f'  .data = {var_name}_map,\n')
        f.write('};\n')
    
    print(f"  ✓ Created {c_file}")
    return True

def main():
    print("LVGL Binary Image Converter")
    print("=" * 50)
    
    # Get script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, 'src')
    
    os.chdir(script_dir)
    
    success_count = 0
    for bin_file, c_file, var_name, width, height in IMAGES:
        c_path = os.path.join(src_dir, c_file)
        if convert_bin_to_c(bin_file, c_path, var_name, width, height):
            success_count += 1
    
    print("=" * 50)
    print(f"Conversion complete: {success_count}/{len(IMAGES)} files converted")
    
    if success_count == len(IMAGES):
        print("\n✓ All images converted successfully!")
        print("  Now run: platformio run --target upload")
    else:
        print("\n⚠ Some files failed to convert. Check that all .bin files are in the project root.")
        return 1
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
